### ISSUE TITLE
V4.1.0 Cannot create a second Character using Hero Mancer

### ISSUE THREAD

**Issue by etoy22** [Sayshal/hero-mancer#28]
After creating the first character using Hero Mancer when attempting to create a second character I get the error that has been attached.

```
Uncaught (in promise) Error: undefined. Failed to render Application "hero-mancer-app":
Cannot read properties of undefined (reading 'start')
[No packages detected]
    at #render (foundry-esm.js:44349:15)
    at async Semaphore._try (foundry-esm.js:6645:19)
```
![image](https://github.com/user-attachments/assets/7e1bb3bf-5b58-4a86-847a-f04e279fee1b)

**Comment by RandomLegend** [comment]
Can confirm, same issue on my side aswell

**Comment by Sayshal** [comment]
I am able to reproduce as well - currently I am focus on a massive new feature to allow Equipment parsing on character sheets. This will be resolved after that.
